### ISSUE TITLE
Implementar Página Inicial/home 

### ISSUE THREAD

**Issue by salazar2112** [gabadias1/coneex#11]
Criar uma página inicial funcional que apresente o login e cadastro e permita fácil acesso às funcionalidades de agenda e gestão de eventos a partir do login.
- [x] Adicionar um painel de boas-vindas ou mensagem de introdução.
- [x] Criar um layout intuitivo e atraente que siga a identidade visual do software.

**Comment by gabadias1** [comment]
feito com sucesso
