### ISSUE TITLE
História de Usuário: editar eventos/contato

### ISSUE THREAD

**Issue by salazar2112** [gabadias1/coneex#7]
Como usuário, eu quero editar um contato na minha agenda, para que eu possa atualizar informações desatualizadas ou corrigir erros.

Critérios de Aceitação:
- [x] O usuário deve ser capaz de selecionar um contato e escolher a opção de edição.
- [x] O sistema deve permitir a edição dos seguintes campos do contato:
- [x] Nome
- [x] Número de telefone
- [x] Endereço de e-mail
- [x] Anotações adicionais (opcional)
- [x] O usuário deve poder salvar as alterações feitas ao contato.
- [x] As alterações feitas no contato devem ser atualizadas na visualização de contatos

**Comment by gabadias1** [comment]
operação de edição concluida
